### ISSUE TITLE
Move main.go, go.mod and go.sum to root of repo

### ISSUE THREAD

**Issue by cooligus** [avorty/spito#39]
Every go repo use this file layout

**Comment by BaderBC** [comment]
Also every other repo in golang does not have `src` folder, link to [reddit discussion](https://www.reddit.com/r/golang/comments/13wy3yr/why_no_src_directory/)

**Comment by cooligus** [comment]
Also we should standardize api layout. In cmd each command has own package. Api layout should also be similar.

**Comment by sewe2000** [comment]
I agree, but in my opinion cmd commands shouldn't be separate packages, because every cmd command consists of at most 2 small files.

**Comment by BaderBC** [comment]
cmd actually should be separate package because it it good practice to separate view from rest of logic. Moreover it is recommended by [cobra](https://cobra.dev/) to create folder `cmd`
