### ISSUE TITLE
`api.pkg.Install`

### ISSUE THREAD

**Issue by BaderBC** [avorty/spito#99]
Impelement api.pkg methods for installing, updating and other stuff related to making changes on packages

It doesn't need to be made using VRCT, meaning I won't be mad if you would install package immediately after calling this method

The only thing you need to worry about is situation when dependency A wants to install package which dependency B wants to uninstall
or situation when dependency A wants to install package 1, dependency B wants to install package 2 while packages 1 and 2 are in conflict

**Comment by sewe2000** [comment]
What do you mean by 'dependencies'? Do you think of the rules or the packages?
